// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRX7d046_xGgGVVqvSvyof5A41xZdM8c',
    appId: '1:589371948155:web:7ea4fa1544937ac58bf6de',
    messagingSenderId: '589371948155',
    projectId: 'lab12-it-firestore-5352b',
    authDomain: 'lab12-it-firestore-5352b.firebaseapp.com',
    storageBucket: 'lab12-it-firestore-5352b.appspot.com',
    measurementId: 'G-E44DDHNW1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC721ptuhUs1VK0qB67tPLk0FqILuQ3gHg',
    appId: '1:589371948155:android:52fcb8b3ed3877ed8bf6de',
    messagingSenderId: '589371948155',
    projectId: 'lab12-it-firestore-5352b',
    storageBucket: 'lab12-it-firestore-5352b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNY5yLgneLrhn09QWkMerR01pWHKjnbw',
    appId: '1:589371948155:ios:5b1eb83b4a8ca3948bf6de',
    messagingSenderId: '589371948155',
    projectId: 'lab12-it-firestore-5352b',
    storageBucket: 'lab12-it-firestore-5352b.appspot.com',
    iosClientId: '589371948155-9j9hn3a8lppp74j2ul6gaoiqoe4lckrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUNY5yLgneLrhn09QWkMerR01pWHKjnbw',
    appId: '1:589371948155:ios:5b1eb83b4a8ca3948bf6de',
    messagingSenderId: '589371948155',
    projectId: 'lab12-it-firestore-5352b',
    storageBucket: 'lab12-it-firestore-5352b.appspot.com',
    iosClientId: '589371948155-9j9hn3a8lppp74j2ul6gaoiqoe4lckrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );
}
